#!/bin/bash

# 讲师端管理系统演示脚本

echo "=========================================="
echo "        讲师端管理系统演示"
echo "=========================================="
echo ""

echo "📚 项目结构："
echo "teacher-frontend/"
echo "├── src/"
echo "│   ├── views/          # 页面组件"
echo "│   │   ├── Dashboard.vue       # 仪表盘"
echo "│   │   ├── CourseManagement.vue # 课程管理"
echo "│   │   ├── StudentManagement.vue # 学生管理"
echo "│   │   └── Login.vue           # 登录页面"
echo "│   ├── components/     # 公共组件"
echo "│   │   └── Layout.vue          # 主布局"
echo "│   ├── router/         # 路由配置"
echo "│   ├── stores/         # 状态管理"
echo "│   ├── api/           # API接口"
echo "│   └── utils/         # 工具函数"
echo "├── package.json       # 项目配置"
echo "└── vite.config.js     # 构建配置"
echo ""

echo "🚀 主要功能："
echo "✅ 用户登录认证"
echo "✅ 响应式仪表盘"
echo "✅ 课程管理（增删改查）"
echo "✅ 学生管理（增删改查）"
echo "✅ 学生课程分配"
echo "✅ 搜索筛选功能"
echo "✅ 批量操作支持"
echo "✅ 数据统计展示"
echo ""

echo "🛠️ 技术栈："
echo "• Vue 3 + Composition API"
echo "• Element Plus UI组件库"
echo "• Pinia 状态管理"
echo "• Vue Router 4 路由"
echo "• Axios HTTP客户端"
echo "• SCSS 样式预处理"
echo "• Vite 构建工具"
echo ""

echo "📱 页面说明："
echo "1. /login - 登录页面（演示账号：teacher/123456）"
echo "2. /dashboard - 仪表盘（数据统计概览）"
echo "3. /courses - 课程管理（课程CRUD操作）"
echo "4. /students - 学生管理（学生CRUD操作）"
echo ""

echo "🎨 界面特性："
echo "• 现代化设计风格"
echo "• 响应式布局"
echo "• 深色主题支持"
echo "• 移动端适配"
echo "• 平滑动画效果"
echo ""

echo "📊 数据展示："
echo "• 总课程数：12门"
echo "• 总学生数：156人"
echo "• 进行中课程：8门"
echo "• 已完成课程：4门"
echo ""

echo "🔧 如何运行（需要Node.js环境）："
echo "1. cd teacher-frontend"
echo "2. npm install"
echo "3. npm run dev"
echo "4. 访问 http://localhost:3000"
echo ""

echo "=========================================="
echo "        项目创建完成！"
echo "=========================================="